// tslint:disable
/**
 * Raiden API
 * https://raiden-network.readthedocs.io/en/stable/rest_api.html
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PaymentReceipt
 */
export interface PaymentReceipt {
  /**
   *
   * @type {string}
   * @memberof PaymentReceipt
   */
  initiator_address: string;
  /**
   *
   * @type {string}
   * @memberof PaymentReceipt
   */
  target_address: string;
  /**
   *
   * @type {string}
   * @memberof PaymentReceipt
   */
  token_address: string;
  /**
   *
   * @type {number}
   * @memberof PaymentReceipt
   */
  amount: number;
  /**
   *
   * @type {number}
   * @memberof PaymentReceipt
   */
  identifier: number;
}
